### ISSUE TITLE
公式推导问题

### ISSUE THREAD

**Issue by iceicea** [xie-lab-ml/Golden-Noise-for-Diffusion-Models#2]
![微信图片_20241211230257](https://github.com/user-attachments/assets/23aefc58-dc25-46b7-94b9-2ab11b33f168)
请问一下这一步是如何得出的?此外下方公式中X_T'与X_T弄混淆了

**Comment by Klayand** [comment]
谢谢您的关注，我们发现了X_T'与X_T弄混了这个问题，后面我们会进行修改，感谢您的帮助。

至于您标红的那一项：
\alpha_T （）括号里面的是，x_{T-K}预测的x_0，然后\alpha_T x_0 + \sigma_T \epsilon到T点，这是标准的DDIM-inversion。希望能解决您的疑虑。

**Comment by iceicea** [comment]
> 谢谢您的关注，我们发现了X_T'与X_T弄混了这个问题，后面我们会进行修改，感谢您的帮助。
> 
> 至于您标红的那一项： \alpha_T （）括号里面的是，x_{T-K}预测的x_0，然后\alpha_T x_0 + \sigma_T \epsilon到T点，这是标准的DDIM-inversion。希望能解决您的疑虑。
为何第二项是σ_T·ε (X_{T-K}, T-K)而非σ_T·ε (X_T, T)

**Comment by iceicea** [comment]
> 谢谢您的关注，我们发现了X_T'与X_T弄混了这个问题，后面我们会进行修改，感谢您的帮助。
> 
> 至于您标红的那一项： \alpha_T （）括号里面的是，x_{T-K}预测的x_0，然后\alpha_T x_0 + \sigma_T \epsilon到T点，这是标准的DDIM-inversion。希望能解决您的疑虑。

为何第二项是σ_T·ε (X_{T-K}, T-K)而非σ_T·ε (X_T, T)

**Comment by shaoshitong** [comment]
因为我们当时只有T-K时刻关于\epsilon的估计，并没有T时刻关于\epsilon的估计。你化简一下就会发现和DDIM-Inversion是完全一致的。
