### ISSUE TITLE
Does this method work with lcm、pcm、sdxl-lightning method？

### ISSUE THREAD

**Issue by fishelegs** [xie-lab-ml/Golden-Noise-for-Diffusion-Models#3]
Does this method work with lcm、pcm、sdxl-lightning method？
Thks!

**Comment by Klayand** [comment]
Definitly, NPNet can be applied directly on these three models. You can directly use the SDXL-checkpoint，after you load the model.

**The second picture in each category is inferred with NPNet.**

1. SDXL-lightning
prompt: **a girl smiling**
![图片](https://github.com/user-attachments/assets/327e56c4-22e5-4109-ac3c-567f0b91f456)
![图片](https://github.com/user-attachments/assets/64ff6ab1-9a0b-447a-943a-42434b147321)

2. LCM
prompt: **Self-portrait oil painting, a beautiful girl with golden hair, 8k**
![图片](https://github.com/user-attachments/assets/48ee7db9-0688-4b4b-aac6-0603952f0b99)
![图片](https://github.com/user-attachments/assets/38964cd9-54e0-40aa-b74a-2656ffb3824c)

3. PCM
prompt: **Self-portrait oil painting, a beautiful girl with golden hair, 8k**
![图片](https://github.com/user-attachments/assets/bc22a3f8-334c-45e6-b1f9-3335ae49d50e)
![图片](https://github.com/user-attachments/assets/a87382d9-b45e-46d5-bf88-c501bb796232)

https://huggingface.co/ByteDance/SDXL-Lightning
https://huggingface.co/latent-consistency/lcm-lora-sdxl
https://github.com/G-U-N/Phased-Consistency-Model
